# -*- coding: utf-8 -*-
"""Mall Customer Segmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12F-eu3BxQIX7lf-J7LMF3L7-yXPD85Ws

# **Mall Customer Segmentation**

Tópicos

1. Introdução
2. Análise exploratória
3. Agrupamento

Um shopping quer segmentar seus clientes para melhorar ações de marketing. Para isso organiza um programa de fidelidade no qual os clientes cadastrads trocam suas notas fiscais de compras em lojas do shopping por bilhetes de um sorteio

O objetivo é:

- Encontrar um conjunto de perfis médios
- Alocar os clientes num perfil mais próximo


Para isso precisamos responder:

- Qual a quantidade de grupos?
- Quais são as características de cada grupo?
- Como calcular a distância entre o grupo e os clientes?

Dataset disponível em: 
https://www.kaggle.com/vjchoudhary7/customer-segmentation-tutorial-in-python

# **Análise exploratória com Python**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

mall = pd.read_csv('https://raw.githubusercontent.com/julliebelmonte/mall-customer-segmentation/main/Mall_Customers.csv', sep = ',')

mall.head()

mall.tail()

mall.shape

mall.info()

"""Remover coluna id

"""

mall = mall.drop('CustomerID', axis=1)

mall.head()

"""Exploração dos dados - resumindo quantitativamente as variáveis numéricas

"""

mall.describe().T

mall[['Gender']].describe().T

"""Visualização de dados """

with sns.axes_style('whitegrid'):
  grafico=sns.boxplot(data=mall, x= 'Age', y= 'Gender', palette='pastel')
  grafico.set(title='Distribuição de idade por sexo', xlabel='Idade', ylabel='Sexo')

with sns.axes_style('whitegrid'):
  grafico=sns.boxplot(data=mall, x= 'Annual Income (k$)', y= 'Gender', palette='pastel')
  grafico.set(title='Distribuição de renda por sexo', xlabel='Renda', ylabel='Sexo')

with sns.axes_style('whitegrid'):
  grafico=sns.boxplot(data=mall, x= 'Spending Score (1-100)', y= 'Gender', palette='pastel')
  grafico.set(title='Distribuição de score por sexo', xlabel='Score', ylabel='Sexo')

with sns.axes_style('whitegrid'):
 grafico= sns.pairplot(data=mall, hue='Gender', palette='pastel')

"""Nota-se que o perfil de compras de clientes de sexo diferentes parece ser o mesmo, foi observado maior concentração entre 30 e 50 anos e pouca variação de gênero, então vamos seguir a analise com os parâmetros: renda, score e idade.

"""

mall = mall.drop('Gender', axis=1)

mall.head()

"""**Agrupamento**: Para agrupar os dados em subgrupos, vamos utilizar um modelo de aprendizado de máquina não supervisionado chamado K-means """

with sns.axes_style('whitegrid'):
  grafico=sns.scatterplot(data=mall, x='Annual Income (k$)', y='Spending Score (1-100)', palette='pastel')
  grafico.set(title='Renda e pontuação', xlabel='Renda anual', ylabel='pontos')
  grafico.figure.set_size_inches(15,7.5)

from sklearn.cluster import KMeans

model= KMeans(n_clusters=5)
model= model.fit(mall)

clusters = model.labels_
clusters = pd.DataFrame(clusters, columns=['cluster'])
clustered_mall= pd.concat([mall, clusters], axis=1)
clustered_mall.head()

with sns.axes_style('whitegrid'):
  grafico= sns.pairplot(data=clustered_mall, hue='cluster', palette='pastel')

"""Com os dados agrupados conseguimos extrair quais são os perfis médios. 

"""

clusters_centers= model.cluster_centers_
clusters_centers= pd.DataFrame(clusters_centers, columns=['Age', 'Annual Income (k$)', 'Spending Score (1-100)'])
clusters_centers.head()

with sns.axes_style('whitegrid'):
  fig, ax =plt.subplots()
  sns.scatterplot(data=clustered_mall, x='Annual Income (k$)', y='Spending Score (1-100)', hue='cluster', palette='pastel', ax=ax)
  sns.scatterplot(data=clusters_centers, x='Annual Income (k$)', y='Spending Score (1-100)', color='black', palette='pastel', ax=ax)

"""**Avaliando**: Seriam 5 o número ideal de grupos?

Para responder vamos utilizar o elbow method que busca balancear o erro e a quantidade de grupos
"""

wcss = []

for k in range(1,11):

  model= KMeans(n_clusters=k)
  model= model.fit(mall)
  wcss.append(model.inertia_)

with sns.axes_style('whitegrid'):
  grafico= sns.lineplot(x=range(1,11), y=wcss, marker='8',palette='pastel')
  grafico.set(title='Método do Cotovelo', ylabel='WCSS(Erro', xlabel='Qtd. clusters');

model= KMeans(n_clusters=5)
model= model.fit(mall)

"""**Estudo dos clusters**"""

with sns.axes_style('whitegrid'):
  grafico=sns.scatterplot(data=clustered_mall.query('cluster==1'), x='Age', y='Annual Income (k$)', hue='cluster', palette='pastel')
  grafico.set(title='Cluster 1 | Distribuição de renda e idade', xlabel= 'Idade',ylabel= 'Renda Anual')
  grafico.get_legend().set_title('Cluster');

"""**Conclusão:** direcionar campanha de marketing para o público acima de 35 anos. clientes com alta renda e baixo potencial de compras poderiam gastar mais."""